import type { Graph, Place, Edge, Profile } from "./types";
const place = (
  id: string,
  name: string,
  floor: 1 | 2,
  kind: Place["kind"],
  x: number,
  y: number,
  notes: string,
): Place => ({
  id,
  name,
  floor,
  kind,
  x,
  y,
  notes,
  verification: "demo",
  observedAt: null,
});
export const nodes: Place[] = [
  place(
    "entrance",
    "Automatic entrance",
    1,
    "entrance",
    80,
    290,
    "Automatic door on this map. Clear width and opening force have not been measured.",
  ),
  place(
    "hall",
    "Main junction",
    1,
    "junction",
    240,
    290,
    "Choose the east or west corridor here.",
  ),
  place(
    "a1",
    "Elevator A · floor 1",
    1,
    "elevator",
    430,
    290,
    "The single planned ultrasonic sensor covers this lobby. Elevator operation is not monitored.",
  ),
  place(
    "bench",
    "Resting bench",
    1,
    "bench",
    240,
    170,
    "A resting point on the west corridor. Seat dimensions are unknown.",
  ),
  place(
    "b1",
    "Elevator B · floor 1",
    1,
    "elevator",
    80,
    90,
    "Alternative elevator. No sensor is assigned to this location.",
  ),
  place(
    "s1",
    "Stairs · floor 1",
    1,
    "stairs",
    430,
    90,
    "Stairs connect floors 1 and 2. Excluded when you choose no stairs.",
  ),
  place(
    "restroom",
    "Restroom",
    1,
    "restroom",
    80,
    170,
    "Restroom; access measurements are unknown.",
  ),
  place(
    "a2",
    "Elevator A · floor 2",
    2,
    "elevator",
    430,
    290,
    "Upper elevator stop on this map.",
  ),
  place(
    "b2",
    "Elevator B · floor 2",
    2,
    "elevator",
    80,
    90,
    "Upper stop of the alternative elevator.",
  ),
  place("s2", "Stairs · floor 2", 2, "stairs", 430, 90, "Upper stair landing."),
  place(
    "upper",
    "Upper junction",
    2,
    "junction",
    240,
    190,
    "Connects the elevators and classroom corridor.",
  ),
  place(
    "classroom",
    "Classroom 201",
    2,
    "classroom",
    240,
    320,
    "Destination. Door width, seating and classroom access are unverified.",
  ),
];
const links: [string, string, number, number, boolean?][] = [
  ["entrance", "hall", 14, 18],
  ["hall", "a1", 18, 23],
  ["a1", "a2", 0, 35],
  ["a2", "upper", 15, 19],
  ["upper", "classroom", 10, 13],
  ["hall", "bench", 12, 16],
  ["bench", "b1", 20, 25],
  ["b1", "b2", 0, 35],
  ["b2", "upper", 25, 32],
  ["hall", "s1", 20, 25],
  ["s1", "s2", 8, 20, true],
  ["s2", "upper", 12, 15],
  ["bench", "restroom", 10, 13],
];
function edge(
  from: string,
  to: string,
  lengthM: number,
  seconds: number,
  stairs = false,
): Edge {
  return {
    id: `${from}-${to}`,
    from,
    to,
    lengthM,
    seconds,
    stairs,
    widthCm: null,
    slopePercent: null,
    surface: null,
    lighting: null,
    closed: false,
    zoneId: from === "a1" || to === "a1" ? "elevator-a-lobby" : null,
    verification: "demo",
  };
}
// 13 forward + 12 explicit reverse edges. The hall → stairs approach is one-way in this schematic.
export const graph: Graph = {
  nodes,
  edges: links.flatMap(([a, b, m, s, stairs], i) =>
    i === 9
      ? [edge(a, b, m, s, stairs)]
      : [edge(a, b, m, s, stairs), edge(b, a, m, s, stairs)],
  ),
};
export const defaultProfile: Profile = {
  noStairs: true,
  lessWalking: false,
  quieter: true,
  resting: false,
  avoidDim: false,
  smoother: false,
  minWidthCm: null,
};
